# Generated by Django 4.2.1 on 2023-06-05 19:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import legasys_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='apellido')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cambio Contraseña',
                'verbose_name_plural': 'Cambio Contraseña',
            },
            managers=[
                ('objects', legasys_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alu_fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_descripcion', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
                ('car_fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crr_descripcion', models.CharField(max_length=100, verbose_name='Carrera')),
                ('crr_fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_descripcion', models.CharField(max_length=100, verbose_name='Nombre de la Facultad')),
                ('fac_fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='LegajoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_tipo', models.CharField(choices=[('Copia', 'Copia'), ('Copia Autenticada', 'Copia Autenticada'), ('Original', 'Original')], max_length=100, verbose_name='Tipo de Documento')),
                ('leg_ruta', models.CharField(max_length=500)),
                ('leg_vencimiento', models.DateField(verbose_name='Vencimiento')),
                ('leg_fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.alumno', verbose_name='Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_descripcion', models.CharField(max_length=100, verbose_name='Nombre del Periodo Lectivo')),
                ('per_fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pln_descripcion', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('pln_fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_descripcion', models.CharField(max_length=100, verbose_name='Resolucion')),
                ('res_numero_resolucionm', models.CharField(max_length=100, verbose_name='Numero de Resolucion')),
                ('res_fecha_resolucion', models.DateField(verbose_name='Fecha de Resolucion')),
                ('res_fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='SedeFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sed_descripcion', models.CharField(max_length=100, verbose_name='Nombre de Sede Filial')),
                ('sed_fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('per_cedula', models.IntegerField(verbose_name='Cédula')),
                ('per_fecha_nacimiento', models.DateField(verbose_name='Fecha de nac.')),
                ('per_telefono', models.IntegerField(verbose_name='Teléfono')),
                ('per_fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('per_direccion', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
            options={
                'abstract': False,
            },
            bases=('legasys_app.baseuser',),
            managers=[
                ('objects', legasys_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_descripcion', models.CharField(max_length=100, verbose_name='Documento')),
                ('doc_vencimiento', models.BooleanField(default=False, verbose_name='Vencimiento')),
                ('doc_fecha_registro', models.DateField(default=datetime.date.today)),
                ('legajo_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.legajoalumno')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSedeFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.carrera', verbose_name='Carrera')),
                ('sedefilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.sedefilial', verbose_name='Sede Filial')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.facultad', verbose_name='Facultad'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_descripcion', models.CharField(max_length=100, verbose_name='Nombre de la Asignatura')),
                ('asi_fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.plan', verbose_name='Plan')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='detallesedefilial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.detallesedefilial', verbose_name='Sede Filial'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.persona', verbose_name='Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_firmante', models.BooleanField(default=False, verbose_name='Es firmante?')),
                ('fun_fecha_registro', models.DateField(default=datetime.date.today)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.cargo', verbose_name='Cargo del Funcionario')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.persona', verbose_name='Funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legasys_app.persona', verbose_name='Alumno/a'),
        ),
    ]
