"""
Django settings for legasys_project project.


Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mirnm(#iai-5awpzm6av9zj+t1(0g@ivqv=2^&581@p7!b@1#v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    #'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'legasys_app',
    #'image',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'legasys_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'legasys_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
    #}
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'legasys',
        'USER': 'root',
        'PASSWORD': '0000',
        'HOST': 'localhost',  # or the hostname where your MySQL server is running
        'PORT': '3306',      # or the port on which your MySQL server is listening
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#Aqui se define donde se guardaran los archivos estaticos
STATIC_URL = 'static/'
STATICFILES_DIRS = str(BASE_DIR.joinpath('static')),
STATIC_ROOT = str(BASE_DIR.joinpath('staticfiles'))
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'legasys_app.BaseUser'

JAZZMIN_SETTINGS = {
    "changeform_format_overrides": {"legasys_app.legajoalumno": "single", "legasys_app.nombramiento": "single"},
    #"show_ui_builder": True,
    #"related_modal_active": True,
    "site_title": "FACITEC by LEGASYS",
    "site_header": "FACITEC",
    "site_brand": "FACITEC",
    "site_logo": "img/logoFacitec.png",
    "welcome_sign": "Bienvenido/a a LEGASYS by: FACITEC",
    "user_avatar": None,

    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        #{"name": "Inicio",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # model admin to link to (Permissions checked against model)
        #{"model": "auth.User"},

        {
            "name": "Constancia",
            "url": "/generate_pdf/",  # URL to your custom view
            "icon": "fas fa-file",   # Icon class
            "permissions": ["auth.view_user"],  # Optional permissions
        },
        {
            "name": "Nombramiento",
            "url": "/generar_nombramiento/",  # URL to your custom view
            "icon": "fas fa-file",   # Icon class
            "permissions": ["auth.view_user"],  # Optional permissions
        },
    ],
    
    "icons": {
        "legasys_app.Alumno": "fas fa-user-graduate",
        "legasys_app.Profesor": "fas fa-user-tie",
        "legasys_app.Funcionario": "fas fa-user",
        "legasys_app.LegajoAlumno": "fas fa-id-card",
        "legasys_app.Nombramiento": "fas fa-crown",
        "legasys_app.TipoDocumento": "fas fa-file",
        "legasys_app.Facultad": "fas fa-school",
        "legasys_app.SedeFilial": "fas fa-map",
        "legasys_app.PeriodoLectivo": "fas fa-calendar",
        "legasys_app.Asignatura": "fas fa-book",
        "legasys_app.Plan": "fas fa-calendar-plus",
        "legasys_app.Cargo": "fas fa-briefcase",
        "legasys_app.CargoProfesor": "fas fa-address-book",
        "legasys_app.CargoProfesorCategoria": "far fa-address-book",
        "legasys_app.Carrera": "fas fa-landmark",
    },
    "hide_models":["legasys_app.NombramientoDetalle", "legasys_app.TipoDocumentoDetalle", "legasys_app.DetalleSedeFilial", "legasys_app.CargoProfesorDetalle", "auth.Group", "legasys_app.Persona"],
    #"site_logo": "img/LogoFaitec.jpg",
    "copyright": "facitec",


}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-light",
    "accent": "accent-danger",
    "navbar": "navbar-danger navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-light-danger",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}

